{
 "title": "Flink RocksDB Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "deploymentName", "query": { "query": "label_values(deploymentName)" } },
   {
    "name": "deploymentId",
    "query": {
     "query": "label_values({deploymentName=~\"$deploymentName\"},deploymentId)"
    }
   },
   {
    "name": "jobName",
    "query": {
     "query": "label_values({deploymentName=~\"$deploymentName\"},job_name)"
    }
   },
   {
    "name": "jobId",
    "query": {
     "query": "label_values({job_name=~\"$jobName\"},jobId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_uptime{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    },
    {
     "title": "Job Restarts",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(flink_jobmanager_job_numRestarts{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}[$__range]))",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Duration",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Records/s" }
   ],
   "targets": [
    {
     "expr": "sum by (jobId, job_name, task_name) (flink_taskmanager_job_task_numRecordsOutPerSecond{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\",task_name=\"UpdateState\"})",
     "legendFormat": "Job {{job_name}} = {{jobId}}: {{task_name}}"
    }
   ]
  },
  {
   "title": "TaskManager Container Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(container_memory_usage_bytes{container=\"flink-taskmanager\",pod=~\"job-$jobId-.*\"}, \"flinkJob\", \"$1\", \"pod\", \"job-($jobId)-.*\")",
     "legendFormat": "Usage {{flinkJob}}"
    },
    {
     "expr": "label_replace(container_spec_memory_limit_bytes{container=\"flink-taskmanager\",pod=~\"job-$jobId-.*\"}, \"flinkJob\", \"$1\", \"pod\", \"job-($jobId)-.*\")",
     "legendFormat": "Limit {{flinkJob}}"
    }
   ]
  },
  {
   "title": "TaskManager Container CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(container_spec_cpu_shares{pod=~\"job-$jobId-taskmanager-.*\",container=\"flink-taskmanager\"}/1024, \"flinkJob\", \"$1\", \"pod\", \"job-($jobId)-.*\")",
     "legendFormat": "Limit {{flinkJob}}"
    },
    {
     "expr": "label_replace(rate(container_cpu_usage_seconds_total{pod=~\"job-$jobId-taskmanager-.*\",container=\"flink-taskmanager\"}[5m]), \"flinkJob\", \"$1\", \"pod\", \"job-($jobId)-.*\")",
     "legendFormat": "Usage {{flinkJob}}"
    }
   ]
  },
  {
   "title": "RocksDB BlockCache Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_block_cache_capacity\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
     "legendFormat": "Capacity {{job_name}}"
    },
    {
     "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_block_cache_usage\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
     "legendFormat": "Usage {{job_name}}"
    },
    {
     "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_block_cache_pinned_usage\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
     "legendFormat": "Pinned {{job_name}}"
    },
    {
     "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_estimate_table_readers_mem\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
     "legendFormat": "Index+Filter {{job_name}}"
    }
   ]
  },
  {
   "title": "RocksDB Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "RocksDB Compaction Flushing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_compaction_pending\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "PendingCompaction {{job_name}}"
      },
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_mem_table_flush_pending\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "PendingFlush {{job_name}}"
      },
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_num_running_compactions\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "RunningCompaction {{job_name}}"
      },
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_num_running_flushes\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "RunningFlush {{job_name}}"
      },
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_estimate_pending_compaction_bytes\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "PendingCompactionBytes {{job_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Memory Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_total_sst_files_size\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "All SST Files {{job_name}}"
      },
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_size_all_mem_tables\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "All Memtables {{job_name}}"
      },
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_estimate_live_data_size\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "Live Data {{job_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Memory Number",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_estimate_num_keys\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "num_keys {{job_name}}"
      },
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_num_live_versions\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "num_vers {{job_name}}"
      },
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*state_rocksdb_num_immutable_mem_table\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "num_im_tables  {{job_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpointing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Checkpoints",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(flink_jobmanager_job_numberOfFailedCheckpoints{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}[$__range]))",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    },
    {
     "title": "Successfull Checkpoints",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(flink_jobmanager_job_numberOfCompletedCheckpoints{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}[$__range]))",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    }
   ]
  }
 ]
}