{
 "title": "Flink Advanced RocksDB Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "deploymentName", "query": { "query": "label_values(deploymentName)" } },
   {
    "name": "deploymentId",
    "query": {
     "query": "label_values({deploymentName=~\"$deploymentName\"},deploymentId)"
    }
   },
   {
    "name": "jobName",
    "query": {
     "query": "label_values({deploymentName=~\"$deploymentName\"},job_name)"
    }
   },
   {
    "name": "jobId",
    "query": {
     "query": "label_values({job_name=~\"$jobName\"},jobId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_uptime{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    },
    {
     "title": "Job Restarts",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(flink_jobmanager_job_numRestarts{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}[$__range]))",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Duration",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Records/s" }
     ],
     "targets": [
      {
       "expr": "sum by (jobId, job_name, task_name) (flink_taskmanager_job_task_numRecordsOutPerSecond{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\",task_name=\"UpdateState\"})",
       "legendFormat": "Job {{job_name}} = {{jobId}}: {{task_name}}"
      }
     ]
    },
    {
     "title": "TaskManager Container Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(container_memory_usage_bytes{container=\"flink-taskmanager\",pod=~\"job-$jobId-.*\"}, \"flinkJob\", \"$1\", \"pod\", \"job-($jobId)-.*\")",
       "legendFormat": "Usage {{flinkJob}}"
      },
      {
       "expr": "label_replace(container_spec_memory_limit_bytes{container=\"flink-taskmanager\",pod=~\"job-$jobId-.*\"}, \"flinkJob\", \"$1\", \"pod\", \"job-($jobId)-.*\")",
       "legendFormat": "Limit {{flinkJob}}"
      }
     ]
    },
    {
     "title": "TaskManager Container CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(container_spec_cpu_shares{pod=~\"job-$jobId-taskmanager-.*\",container=\"flink-taskmanager\"}/1024, \"flinkJob\", \"$1\", \"pod\", \"job-($jobId)-.*\")",
       "legendFormat": "Limit {{flinkJob}}"
      },
      {
       "expr": "label_replace(rate(container_cpu_usage_seconds_total{pod=~\"job-$jobId-taskmanager-.*\",container=\"flink-taskmanager\"}[5m]), \"flinkJob\", \"$1\", \"pod\", \"job-($jobId)-.*\")",
       "legendFormat": "Usage {{flinkJob}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpointing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Checkpoints",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(flink_jobmanager_job_numberOfFailedCheckpoints{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}[$__range]))",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    },
    {
     "title": "Successfull Checkpoints",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(increase(flink_jobmanager_job_numberOfCompletedCheckpoints{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}[$__range]))",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{deploymentId=~\"$deploymentId\",jobId=~\"$jobId\"}",
       "legendFormat": "Job {{job_id}}"
      }
     ]
    }
   ]
  },
  { "title": "RocksDB Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "RocksDB BlockCache Capacity",
   "type": "stat",
   "description": "Monitor block cache capacity.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_capacity\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "{{column_family}}"
    }
   ]
  },
  {
   "title": "RocksDB Background Errors",
   "type": "stat",
   "description": "Monitor the number of background errors in RocksDB.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_background_errors\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Bg Err {{job_name}}"
    }
   ]
  },
  {
   "title": "RocksDB Actual Delayed Write Rate",
   "type": "stat",
   "description": "Monitor the current actual delayed write rate. 0 means no delay.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_actual_delayed_write_rate\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Delayed Write Rate {{job_name}}"
    }
   ]
  },
  {
   "title": "RocksDB Estimate Table Readers Memory",
   "type": "stat",
   "description": "Estimate the memory used for reading SST tables, excluding memory used in block cache (e.g.,filter and index blocks) in bytes.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_table_readers_mem\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Index+Filter {{job_name}}"
    }
   ]
  },
  {
   "title": "RocksDB Num Live Versions",
   "type": "stat",
   "description": "Monitor number of live versions. Version is an internal data structure. See RocksDB file version_set.h for details. More live versions often mean more SST files are held from being deleted, by iterators or unfinished compactions.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_num_live_versions\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "num_vers {{job_name}}"
    }
   ]
  },
  {
   "title": "RocksDB Is Write Stopped",
   "type": "stat",
   "description": "Track whether write has been stopped in RocksDB. Returns 1 if write has been stopped, 0 otherwise.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_is_write_stopped\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Wrt Stopped  {{job_name}}"
    }
   ]
  },
  {
   "title": "RocksDB Estimate Num Keys",
   "type": "stat",
   "description": "Estimate the number of keys in RocksDB.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_num_keys\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "num_keys {{job_name}}"
    }
   ]
  },
  {
   "title": "RocksDB Num Immutable Memtable",
   "type": "stat",
   "description": "Monitor the number of immutable memtables in RocksDB.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_num_immutable_mem_table\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "num_im_tables  {{job_name}}"
    }
   ]
  },
  {
   "title": "RocksDB Running Compactions & Flushes",
   "type": "graph",
   "description": "Monitor the number of currently running compactions and flushes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_num_running_compactions\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Compaction {{column_family}}"
    },
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_num_running_flushes\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Flush {{column_family}}"
    }
   ]
  },
  {
   "title": "RocksDB Pending Compactions & Flushes",
   "type": "graph",
   "description": "Track pending compactions and flushes in RocksDB. Returns 1 if a compaction/flush is pending, 0 otherwise.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_compaction_pending\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Compaction {{column_family}}"
    },
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_mem_table_flush_pending\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Flush {{column_family}}"
    }
   ]
  },
  {
   "title": "RocksDB Estimate Pending Compaction Bytes",
   "type": "graph",
   "description": "Estimated total number of bytes compaction needs to rewrite to get all levels down to under target size. Not valid for other compactions than level-based.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_pending_compaction_bytes\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "{{column_family}}"
    }
   ]
  },
  {
   "title": "RocksDB BlockCache Usage",
   "type": "graph",
   "description": "Monitor the memory size for the entries being pinned in block cache and residing in block cache.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_pinned_usage\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Pinned {{column_family}}"
    },
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_usage\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Usage {{column_family}}"
    }
   ]
  },
  {
   "title": "RocksDB Memtables Size",
   "type": "graph",
   "description": "Monitor the approximate size of the memtables in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_cur_size_active_mem_table\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Active {{column_family}}"
    },
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_cur_size_all_mem_tables\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Active+Imm {{column_family}}"
    },
    {
     "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*_rocksdb_size_all_mem_tables\",deploymentId=~\"$deploymentId\",jobId=~\"$jobId\", column_family=~\".*state\"}",
     "legendFormat": "Active+Imm+Pinned {{column_family}}"
    }
   ]
  },
  {
   "title": "RocksDB Total Size",
   "type": "graph",
   "description": "Monitor the total size (bytes) of all SST files and live data.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "All SST Files {{column_family}}"
    },
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_live_data_size\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Live Data {{column_family}}"
    }
   ]
  },
  {
   "title": "RocksDB Num Entries in Memtables",
   "type": "graph",
   "description": "Monitor the total number of entries in the memtables.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_num_entries_active_mem_table\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Active Memtable {{column_family}}"
    },
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_num_entries_imm_mem_tables\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Imm Memtables {{column_family}}"
    }
   ]
  },
  {
   "title": "RocksDB Num Deletes in Memtables",
   "type": "graph",
   "description": "Monitor the total number of delete entries in the memtables.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_num_deletes_active_mem_table\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Active Memtable {{column_family}}"
    },
    {
     "expr": "{__name__=\"flink_taskmanager_job_task_operator_column_family_rocksdb_num_deletes_imm_mem_tables\",deploymentId=\"$deploymentId\",jobId=\"$jobId\",column_family=~\".*state\"}",
     "legendFormat": "Imm Memtables {{column_family}}"
    }
   ]
  }
 ]
}